CREATE TABLE USUARIO(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR(50) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    ADMIN BOOL DEFAULT FALSE
);
CREATE TABLE VIDEO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    ASSUNTO VARCHAR(128),
    DESCRICAO VARCHAR(1000),
    URL VARCHAR(200),
    COMMENT_ID INTEGER REFERENCES COMMENT (ID),
    USUARIO_ID INTEGER REFERENCES USUARIO_ID
);
CREATE TABLE COMMENT (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    COMMENTS VARCHAR(2000),
    LIKES BOOLEAN(),
    VIDEO_ID INTEGER REFERENCES VIDEO (ID),
    USUARIO_ID INTEGER REFERENCES USUARIO_ID

);

